# Generated by Django 3.1 on 2020-09-08 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('eco', models.CharField(max_length=3)),
                ('moves', models.TextField()),
                ('opening_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insight.openingsystem')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo_mean', models.IntegerField(default=0)),
                ('elo_diff', models.IntegerField(default=0)),
                ('result', models.CharField(max_length=40)),
                ('timecontrol', models.CharField(max_length=40)),
                ('timestamp', models.DateTimeField()),
                ('raw', models.TextField()),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insight.opening')),
            ],
        ),
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turnover_move', models.IntegerField(default=0)),
                ('turnover_evaluation', models.IntegerField(default=0)),
                ('unbalance_material', models.IntegerField(default=0)),
                ('unbalance_officers', models.IntegerField(default=0)),
                ('unbalance_exchange', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insight.game')),
            ],
        ),
    ]
