# Generated by Django 3.1 on 2020-08-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0002_auto_20200831_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='elo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='skill',
            field=models.CharField(default='Peon', max_length=40),
        ),
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
