# Generated by Django 3.1 on 2020-09-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0003_analyse'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.AddField(
            model_name='game',
            name='elo_diff',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='elo_mean',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
